DROP TABLE IF EXISTS `messages`;
CREATE TABLE IF NOT EXISTS `messages` (
  `view` varchar(31) COLLATE utf8_unicode_ci NOT NULL,
  `message` text COLLATE utf8_unicode_ci,
  `name` varchar(63) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`view`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `messages`
--

INSERT INTO `messages` (`view`, `message`, `name`) VALUES
('cncpslip', '<p>Date:_______________<br /><br />WT: _____ LBS.<br /><br />BOX SIZE _____ &nbsp; &nbsp;L &nbsp;* ______ &nbsp;W &nbsp;*_____ &nbsp;H<br /><br />PRICE $ _______________</p>', 'CNC''s Packing Slip'),
('custpslip', '<p><strong>*** ATTENTION : RECEIVING DEPARTMENT ***</strong><br />This item must be <strong>tested within 5 days</strong> of receipt and checked for any shipping damages. &nbsp;Please advise our office ASAP if there are any problems.</p>\n<p>Thank you,<br />&nbsp; &nbsp; - CNC REPAIR&nbsp;1-877-262-7372</p>', 'Customer''s Packing Slip'),
('hours', 'Mon-Thurs: 8:30-4:30 / Fri: 7:00-2:00 PST', 'Hours'),
('html_email', '<p>Thank you for requesting a quote from CNCrepair.com! Your PDF quote is attached.</p>\n<p>Cncrepair.com has:</p>\n<ul>\n<li>Servo / Axis Drives:<br />\n<ul>\n<li>Yaskawa: CACR-SR, CACR-IR, CPCR-MR, &amp; MORE</li>\n<li>Okuma: BDU, BL-D, BL2-D exchanges in stock</li>\n<li>Mitsubishi: Fanuc: Fanuc 6, Fanuc 10, Fanuc 11 &amp; MORE</li>\n<li>Hitachi Seiki: ADU-, ASU-</li>\n<li>Sanyo Denki:</li>\n</ul>\n</li>\n<li>Spindle Drives:\n<ul>\n<li>Okuma: VAC1, VAC2, VAC3, MIP, MIV</li>\n<li>Fanuc: A06B-6041-xxxx, A06B-6044-xxxx, A06B-6058-xxx &amp; MORE</li>\n<li>Yaskawa: 505-MT, 626-MT, 626-MT2, 626-MT2B, 626-MT3, CIMR-VMW, CIMR-VMS &amp; MORE</li>\n<li>Mitsubishi: FR-SX, FR-SE, FR-SF, DL-SCZ &amp; MORE</li>\n<li>Allen Bradley: 1391-AA &amp; MORE</li>\n</ul>\n</li>\n<li>Power Supplies:\n<ul>\n<li>Hitachi Seiki:&nbsp;ED136, ED139, HS-01, &amp; MORE</li>\n<li>Okuma: everything for Okuma 5000 &amp; 5020, U100, &amp; MORE</li>\n<li>Fanuc 6, Fanuc 10, Fanuc 11, &amp; MORE</li>\n<li>Yasnac: CPS-10, CPS-10NB, CPS-20, CPS-20N, CPS-12, &amp; MORE</li>\n<li>Mitsubishi: SF-PW, SE-PW, PD-21B, &amp; MOR</li>\n</ul>\n</li>\n<li>CRT &amp; LCD Monitors:\n<ul>\n<li>LCDs: Replacements for 12" and 14" CRTs</li>\n<li>All 9" &amp; 12" monochrome monitors.</li>\n<li>Fanuc, Yaskawa, Okuma, Hitachi, Siemens, Hurco, &amp; MORE</li>\n</ul>\n</li>\n<li>Motherboards, etc.:\n<ul>\n<li>Fanuc, Okuma, Hitachi Seiki.</li>\n</ul>\n</li>\n</ul>\n<p>Call with your part number and complete description of the problem.</p>\n<p><strong>For paperwork &amp; logistic questions: Lindsay Thorley, office manager&nbsp;</strong><br /><strong>For troubleshooting help: Jim Leuba, engineer&nbsp;</strong></p>\n<p>1770 Front ST # 142<br />Lynden, WA 98264 USA<br />voice: 408-331-1970<br />fax: 866-313-6101</p>', 'HTML Email'),
('inv', '<p>Testing ivoice message</p>', 'Invoice'),
('quoteexch', '<p><strong><span style="text-decoration: underline;">To activate this quote</span></strong>: Complete attached Credit Card Authorization form, provide your company info, and specify shipping method.&nbsp; To ensure proper credit, please return your dud/core in <em>the original box using all received packing materials</em>.&nbsp; Items returned with SHIPPING DAMAGE OR FAILED REPAIR ATTEMPTS may not be suitable for exchange and will incur <em>additional charges</em>. &nbsp;<strong>Duds/Cores are to be returned within 10 days. &nbsp;Customer responsible for return freight.&nbsp; Cores damaged by repair attempts or not returned within 30 days will be charged a replacement fee which could EXCEED 10 TIMES the purchase price.</strong> &nbsp;Our exchange and repair pricing is based on typical "in use" failures. &nbsp;Exceptional damage will increase your cost. &nbsp;Thank you!</p>\n<p>&nbsp;</p>\n<h3 style="text-align: center;">*PLEASE NOTE: Due to US Customs regulations, ANY ITEM VALUED OVER $2000 WILL BE SHIPPED DIRECTLY &nbsp;FROM OUR REPAIR FACILITY IN CANADA. MAKE SURE OUR OFFICE HAS your VALID TAX ID #&nbsp;</h3>\n<p>Purchase Order # (for your use): ___________________________</p>\n<p>If shipping information is not specified, we will ship via UPS 3-day and add the charge to your invoice.<br /> Return Shipping Carrier: ______________________&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Account: _______________________<br /> Please circle return shipping preference:&nbsp;&nbsp;&nbsp; (1-day)&nbsp;&nbsp; (2-day)&nbsp;&nbsp; (3-day)&nbsp;&nbsp; (Ground)</p>\n<p>For orders over US$2000.00, the US Gov. requires that we record your Employer Identification Number (EIN) or Tax ID Number.<br /> EIN/Tax ID #: ________________________</p>\n<p>There is a 15% re-stocking fee on unused items returned to our office within 15 days.</p>\n<div id="signatureBox"><strong style="font-size: 16pt;">Authorized Signature:</strong>_____________________________</div>\n<p>&nbsp;</p>', 'Quote - Exchange'),
('quoterepair', '<p><strong><span style="text-decoration: underline;">To activate this quote</span></strong>: Complete attached Credit Card Authorization form, provide your company info, and specify shipping method. &nbsp;The Quote # is your Return Authorization # (RA#). &nbsp;All items must be packed carefully and protected from contamination. &nbsp;Enclose your item in a plastic bag! &nbsp;See attached packing information or call our office for assistance. &nbsp;<strong>Attach this Quote to the OUTSIDE of your shipping box and confirm serial numbers are correct.</strong> &nbsp;&nbsp; Our repair pricing is based on typical "in use" failures. &nbsp;Exceptional damage (or failed repair attempts) will increase your cost. &nbsp;Thank you! &nbsp;</p>\n<p>&nbsp;</p>\n<h3 style="text-align: center;">*Due to US Customs regulations, ANY ITEM VALUED OVER $2000 WILL BE SHIPPED DIRECTLY &nbsp;FROM OUR REPAIR FACILITY IN CANADA. MAKE SURE OUR OFFICE HAS your VALID TAX ID # &nbsp;</h3>\n<p>Purchase Order # (for your use): ___________________________</p>\n<p>If shipping information is not specified, we will ship via UPS 3-day and add the charge to your invoice.<br /> Return Shipping Carrier: ______________________&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Account: _______________________<br /> Please circle return shipping preference:&nbsp;&nbsp;&nbsp; (1-day)&nbsp;&nbsp; (2-day)&nbsp;&nbsp; (3-day)&nbsp;&nbsp; (Ground)</p>\n<p>For orders over US$2000.00, the US Gov. requires that we record your Employer Identification Number (EIN) or Tax ID Number.<br /> EIN/Tax ID #: ________________________</p>\n<p>There is a 15% re-stocking fee on unused items returned to our office within 15 days.</p>\n<div id="signatureBox"><strong style="font-size: 16pt;">Authorized Signature:</strong>_____________________________</div>', 'Quote - Repair'),
('quotesale', '<p><strong><span style="text-decoration: underline;">To activate this quote</span></strong>: Complete attached Credit Card Authorization form, provide your company info, and specify shipping method. &nbsp;Thank you!</p>\n<p>&nbsp;</p>\n<h3>&nbsp; &nbsp; &nbsp;*Due to US Customs regulations, ANY ITEM VALUED OVER $2000 WILL BE SHIPPED DIRECTLY &nbsp;FROM OUR REPAIR FACILITY IN CANADA. MAKE SURE OUR OFFICE HAS your VALID TAX ID # &nbsp;</h3>', 'Quote - Sale'),
('rma', '<p>To insure proper credit, please return this RMA and your dud/core in THE ORIGINAL BOX. USE ALL RECEIVED PACKING MATERIAL. <br /><br />Items returned with shipping damage may not be suitable for exchange and may incur and additional charge. <br /><br /><strong>DUD ITEM SERIAL NUMBER.____________________________</strong><br /><br />PLEASE SUPPLY DUD ITEM''S SERIAL NUMBER ABOVE. <br /><br />USE A PLASTIC POUCH TO ATTACH THIS RMA TO THE RETURN BOX. This will speed-up crediting your account.<br /><br />Ship to:</p>\n<p><strong>CNC Repair &amp; Sales<br /></strong>1770 Front Street #142<br /> Lynden, WA 98264 USA<br /><br /><span style="text-decoration: underline;"><strong>ALL EXCHANGES MUST BE RETURNED WITHIN 10 DAYS, freight prepaid.</strong></span> CORES NOT RETURNED WITHIN 30 DAYS WILL BE CHARGED A REPLACEMENT FEE WHICH COULD EXCEED 10 TIMES THE PURCHASE PRICE. We do not sell cores!. All items must be protected from packing material, enclose your dud in a plastic bag.<br />THANK YOU<strong><span style="text-decoration: underline;"><br /></span></strong></p>', 'Return Authorization'),
('text_email', 'Thank you for requesting a quote from CNCrepair.com!  Your PDF quote is attached.\n \nCNCrepair.com has:\n\nServo / Axis Drives:\nYaskawa: CACR-SR, CACR-IR, CPCR-MR, & MORE\nOkuma: BDU, BL-D, BL2-D exchanges in stock\nMitsubishi:\nFanuc: Fanuc 6, Fanuc 10, Fanuc 11 & MORE\nHitachi Seiki: ADU-, ASU-\nSanyo Denki:\n\nSpindle Drives:\nOkuma: VAC1, VAC2, VAC3, MIP, MIV\nFanuc: A06B-6041-xxxx, A06B-6044-xxxx, A06B-6058-xxx & MORE\nYaskawa: 505-MT, 626-MT, 626-MT2, 626-MT2B, 626-MT3, CIMR-VMW, CIMR-VMS & MORE\nMitsubishi: FR-SX, FR-SE, FR-SF, DL-SCZ & MORE\nAllen Bradley: 1391-AA & MORE\n\nPower Supplies:\nHitachi Seiki: ED136, ED139, HS-01, & MORE\nOkuma: everything for Okuma 5000 & 5020, U100, & MORE\nFanuc 6, Fanuc 10, Fanuc 11, & MORE\nYasnac: CPS-10, CPS-10NB, CPS-20, CPS-20N, CPS-12, & MORE\nMitsubishi: SF-PW, SE-PW, PD-21B, & MORE\n\nCRT & LCD Monitors:\nLCDs: Replacements for 12" and 14" CRTs\nAll 9" & 12" monochrome monitors.\nFanuc, Yaskawa, Okuma, Hitachi, Siemens, Hurco, & MORE\n\nMotherboards, etc.:\nFanuc, Okuma, Hitachi Seiki.\n\nCall with your part number and complete description of the problem.\n\nFor paperwork & logistic questions: Lindsay Thorley, office manager\nFor troubleshooting help: Jim Leuba, engineer\n\ncncrepair.com\n1770 Front ST # 142\nLynden, WA 98264 USA\n\nvoice: 408-331-1970\nfax: 866-313-6101', 'Text Email');
